#!/bin/bash
help() {
    cat << EOF

# Usage
./this-script help

# Commands
help - Print this help message
initialise - terragrunt apply - (re)init infrastructure
reinitialise - destroy and init the droplet - for testing cloud-init or whatever
hibernate - terragrunt destroy *all but persistent storage*
die - terragrunt destroy *all*
log - stream cloud init log from droplet
connect - ssh to the droplet
ping - pong

EOF
}

initialise() {
    echo "Applying infrastructure"
    echo

    terragrunt apply
}

reinitialise() {
    echo "Destroying droplet"
    echo

    terragrunt destroy -target digitalocean_droplet.droplet

    echo "Initialising droplet"
    echo

    terragrunt apply
}

hibernate() {
    echo "Destroying everything but the persistent volume"
    echo

    terragrunt destroy -target digitalocean_droplet.droplet -target digitalocean_floating_ip.droplet_ip
}

log() {
    # StrictHostKeyChecking disabled, because I regenerate the droplet all the time for testing
    # and therefore the host key changes and I don't want to manually remove it.
    ssh -o StrictHostKeyChecking=no "user@$(terraform output droplet_ip)" -i ~/.ssh/id_rsa.key \
        "tail -f /var/log/cloud-init.log"
}

connect() {
    ssh -o StrictHostKeyChecking=no -t "user@$(terraform output droplet_ip)" -i ~/.ssh/id_rsa.key
}

die() {
    terragrunt destroy
}

ping() {
    echo "pong"
}

# No arguments handle
if [[ $# -eq 0 ]]
then
    help
    exit 0
fi

# If given parameter isn't a defined function handle
if ! [[ "$1" =~ ^(help|initialise|reinitialise|hibernate|die|log|connect|ping)$ ]]
then
    echo "Sorrjan, but command '$1' not found."
    help
else
    eval $1
fi
