#!/usr/bin/env bash

set -eux

cd "$(dirname "$0")"

install-chef() {
    apt update
    apt install -y wget build-essential ruby ruby-dev autoconf libffi6 libffi-dev

    curl -sLO "https://omnitruck.chef.io/install.sh" | bash -s 13.6

    gem update --system
    gem install --no-rdoc --no-ri berkshelf 2> /dev/null || true
}

command -v chef-client || install-chef

git fetch
git checkout -f origin/master

berks vendor cookbooks

chef-client -zr 'role[main]'
