#cloud-config

write_files:
  - path: /root/init-vm
    permissions: '0755'
    content: |
${init_script}

users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - |
${public_key}

runcmd:
  - [ /root/init-vm, "${source}", "${project_code}" ]

output: { all: "| tee -a /var/log/cloud-init.log" }